config/routes.rb
SistemaLibrosApucv::Application.routes.draw do
  
  resources :usuario_solicituds

  resources :usuario_libros

  resources :libros

  resources :condicions

  resources :modalidads

  resources :usuarios

  get ':controller(/:action(/:id(.:format)))'
  post ':controller(/:action(/:id(.:format)))'
  root 'sesion#index'

end

app/models/condicion.rb
class Condicion < ActiveRecord::Base
end

app/controllers/condicions_controller.rb
class CondicionsController < ApplicationController
  before_action :set_condicion, only: [:show, :edit, :update, :destroy]

 
  # GET /condicions/new
  def new
    @condicion = Condicion.new
  end

  # GET /condicions/1/edit
  def edit
  end

  # POST /condicions
  # POST /condicions.json
  def create
    @condicion = Condicion.new(condicion_params)

    respond_to do |format|
      if @condicion.save
        format.html { redirect_to @condicion, notice: 'Condicion was successfully created.' }
        format.json { render action: 'show', status: :created, location: @condicion }
      else
        format.html { render action: 'new' }
        format.json { render json: @condicion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /condicions/1
  # PATCH/PUT /condicions/1.json
  def update
    respond_to do |format|
      if @condicion.update(condicion_params)
        format.html { redirect_to @condicion, notice: 'Condicion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @condicion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /condicions/1
  # DELETE /condicions/1.json
  def destroy
    @condicion.destroy
    respond_to do |format|
      format.html { redirect_to condicions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_condicion
      @condicion = Condicion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def condicion_params
      params.require(:condicion).permit(:id_condicion, :descripcion)
    end
end

app/helpers/condicions_helper.rb
module CondicionsHelper
end

app/views/condicions/_form.html.erb
<%= form_for(@condicion) do |f| %>
  <% if @condicion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@condicion.errors.count, "error") %> prohibited this condicion from being saved:</h2>

      <ul>
      <% @condicion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_condicion %><br>
    <%= f.text_field :id_condicion %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/condicions/edit.html.erb
<h1>Editing condicion</h1>

<%= render 'form' %>

<%= link_to 'Show', @condicion %> |
<%= link_to 'Back', condicions_path %>

app/views/condicions/new.html.erb
<h1>New condicion</h1>

<%= render 'form' %>

<%= link_to 'Back', condicions_path %>