config/routes.rb
SistemaLibrosApucv::Application.routes.draw do
  
  resources :usuario_solicituds

  resources :usuario_libros

  resources :libros

  resources :condicions

  resources :modalidads

  resources :usuarios

  get ':controller(/:action(/:id(.:format)))'
  post ':controller(/:action(/:id(.:format)))'
  root 'sesion#index'

end

app/models/usuario_libro.rb
class UsuarioLibro < ActiveRecord::Base
	belongs_to :usuario
	belongs_to :libro
end

app/controllers/usuario_libros_controller.rb
class UsuarioLibrosController < ApplicationController
  before_action :set_usuario_libro, only: [:show, :edit, :update, :destroy]


  # GET /usuario_libros/new
  def new
    @usuario_libro = UsuarioLibro.new
  end

  # GET /usuario_libros/1/edit
  def edit
  end

  # POST /usuario_libros
  # POST /usuario_libros.json
  def create
    @usuario_libro = UsuarioLibro.new(usuario_libro_params)

    respond_to do |format|
      if @usuario_libro.save
        format.html { redirect_to @usuario_libro, notice: 'Usuario libro was successfully created.' }
        format.json { render action: 'show', status: :created, location: @usuario_libro }
      else
        format.html { render action: 'new' }
        format.json { render json: @usuario_libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuario_libros/1
  # PATCH/PUT /usuario_libros/1.json
  def update
    respond_to do |format|
      if @usuario_libro.update(usuario_libro_params)
        format.html { redirect_to @usuario_libro, notice: 'Usuario libro was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @usuario_libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuario_libros/1
  # DELETE /usuario_libros/1.json
  def destroy
    @usuario_libro.destroy
    respond_to do |format|
      format.html { redirect_to usuario_libros_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario_libro
      @usuario_libro = UsuarioLibro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_libro_params
      params.require(:usuario_libro).permit(:id_libro, :id_usuario)
    end
end

app/helpers/usuario_libros_helper.rb
module UsuarioLibrosHelper
end

app/views/usuario_libros/_form.html.erb
<%= form_for(@usuario_libro) do |f| %>
  <% if @usuario_libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario_libro.errors.count, "error") %> prohibited this usuario_libro from being saved:</h2>

      <ul>
      <% @usuario_libro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_libro %><br>
    <%= f.text_field :id_libro %>
  </div>
  <div class="field">
    <%= f.label :id_usuario %><br>
    <%= f.text_field :id_usuario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuario_libros/edit.html.erb
<h1>Editing usuario_libro</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario_libro %> |
<%= link_to 'Back', usuario_libros_path %>

app/views/usuario_libros/new.html.erb
<h1>New usuario_libro</h1>

<%= render 'form' %>

<%= link_to 'Back', usuario_libros_path %>