config/routes.rb
SistemaLibrosApucv::Application.routes.draw do
  
  resources :usuario_solicituds

  resources :usuario_libros

  resources :libros

  resources :condicions

  resources :modalidads

  resources :usuarios

  get ':controller(/:action(/:id(.:format)))'
  post ':controller(/:action(/:id(.:format)))'
  root 'sesion#index'

end

app/models/usuario_solicitud.rb
class UsuarioSolicitud < ActiveRecord::Base
end

app/controllers/usuario_solicituds_controller.rb
class UsuarioSolicitudsController < ApplicationController
  before_action :set_usuario_solicitud, only: [:show, :edit, :update, :destroy]



  # GET /usuario_solicituds/new
  def new
    @usuario_solicitud = UsuarioSolicitud.new
  end

  # GET /usuario_solicituds/1/edit
  def edit
  end

  # POST /usuario_solicituds
  # POST /usuario_solicituds.json
  def create
    @usuario_solicitud = UsuarioSolicitud.new(usuario_solicitud_params)

    respond_to do |format|
      if @usuario_solicitud.save
        format.html { redirect_to @usuario_solicitud, notice: 'Usuario solicitud was successfully created.' }
        format.json { render action: 'show', status: :created, location: @usuario_solicitud }
      else
        format.html { render action: 'new' }
        format.json { render json: @usuario_solicitud.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuario_solicituds/1
  # PATCH/PUT /usuario_solicituds/1.json
  def update
    respond_to do |format|
      if @usuario_solicitud.update(usuario_solicitud_params)
        format.html { redirect_to @usuario_solicitud, notice: 'Usuario solicitud was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @usuario_solicitud.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuario_solicituds/1
  # DELETE /usuario_solicituds/1.json
  def destroy
    @usuario_solicitud.destroy
    respond_to do |format|
      format.html { redirect_to usuario_solicituds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario_solicitud
      @usuario_solicitud = UsuarioSolicitud.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_solicitud_params
      params.require(:usuario_solicitud).permit(:id_libro, :id_usuario, :fecha_solicitud)
    end
end

app/helpers/usuario_solicituds_helper.rb
module UsuarioSolicitudsHelper
end

app/views/usuario_solicituds/_form.html.erb
<%= form_for(@usuario_solicitud) do |f| %>
  <% if @usuario_solicitud.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario_solicitud.errors.count, "error") %> prohibited this usuario_solicitud from being saved:</h2>

      <ul>
      <% @usuario_solicitud.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_libro %><br>
    <%= f.text_field :id_libro %>
  </div>
  <div class="field">
    <%= f.label :id_usuario %><br>
    <%= f.text_field :id_usuario %>
  </div>
  <div class="field">
    <%= f.label :fecha_solicitud %><br>
    <%= f.date_select :fecha_solicitud %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuario_solicituds/edit.html.erb
<h1>Editing usuario_solicitud</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario_solicitud %> |
<%= link_to 'Back', usuario_solicituds_path %>

app/views/usuario_solicituds/new.html.erb
<h1>New usuario_solicitud</h1>

<%= render 'form' %>

<%= link_to 'Back', usuario_solicituds_path %>