config/routes.rb
SistemaLibrosApucv::Application.routes.draw do
  
  resources :usuario_solicituds

  resources :usuario_libros

  resources :libros

  resources :condicions

  resources :modalidads

  resources :usuarios

  get ':controller(/:action(/:id(.:format)))'
  post ':controller(/:action(/:id(.:format)))'
  root 'sesion#index'

end

app/models/libro.rb
class Libro < ActiveRecord::Base
	belongs_to :modalidad
	belongs_to :condicion

	has_many :usuario_libro 
	has_many :usuario, through: :usuario_libro
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy]

  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.all
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros
  # POST /libros.json
  def create
    flash[:mensaje]= false
    @libro = Libro.new
    @libro.titulo= params[:titulo]
    @libro.autor= params[:autor]
    @libro.editorial= params[:editorial]
    @libro.condicion_id= params[:condicion]
    @libro.modalidad_id= params[:modalidad]
    @libro.ano= params[:ano]
    @libro.solicitado= 0
    @libro.disponible= 1
    t = Time.now
    date = t.year.to_s+"-"+t.month.to_s+"-"+t.day.to_s
    @libro.fecha_inicio= date
    @libro.usuario_id= session[:id]
    if @libro.save
      flash[:mensaje]= "El libro fue agregado satisfactoriamente"
      redirect_to controller: :gestion, action: :agregarl
    else
      flash[:mensaje]="Ocurrio un error creando el libro, por favor intentelo de nuevo"
      redirect_to controller: :gestion, action: :agregarl
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json


  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/libros/_form.html.erb
<%= form_for(@libro) do |f| %>
  <% if @libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
      <% @libro.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :editorial %><br>
    <%= f.text_field :editorial %>
  </div>
  <div class="field">
    <%= f.label :id_condicion %><br>
    <%= f.text_field :id_condicion %>
  </div>
  <div class="field">
    <%= f.label :id_modalidad %><br>
    <%= f.text_field :id_modalidad %>
  </div>
  <div class="field">
    <%= f.label :ano %><br>
    <%= f.text_field :ano %>
  </div>
  <div class="field">
    <%= f.label :disponible %><br>
    <%= f.text_field :disponible %>
  </div>
  <div class="field">
    <%= f.label :fecha_inicio %><br>
    <%= f.date_select :fecha_inicio %>
  </div>
  <div class="field">
    <%= f.label :id_usuario %><br>
    <%= f.text_field :id_usuario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/libros/edit.html.erb
<h1>Editing libro</h1>

<%= render 'form' %>

<%= link_to 'Show', @libro %> |
<%= link_to 'Back', libros_path %>

app/views/libros/new.html.erb
<h1>New libro</h1>

<%= render 'form' %>

<%= link_to 'Back', libros_path %>